[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "{{cookiecutter.project_name}}"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = ["ninja", "-C", "build"], depends-on = ["configure"]}
configure = { cmd = ["cmake", "-G", "Ninja", "-S", "{{cookiecutter.mitsuba_path}}", "-B", "build"] }

[feature.clang.tasks]
configure = { cmd = ["cmake", "-D", "CMAKE_C_COMPILER=clang", "-D", "CMAKE_CXX_COMPILER=clang++", "-G", "Ninja", "-S", "{{cookiecutter.mitsuba_path}}", "-B", "build"] }


[environments]
clang = ["clang"]

[dependencies]

cmake = "3.28"
cuda = "12.4"
gcc = "13.2.*"
gxx = "13.2.*"
python = "3.11"
zlib = "1.3.1"
pkg-config = ">=0.29.2,<0.30"
clang = ">=19.1.1,<20"
clangxx = ">=19.1.1,<20"
embree = ">=4.3.3,<5"

[target.linux-64.activation.env]
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
