[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "{{cookiecutter.project_name}}"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test-mitsuba = { cmd = "python -m pytest", cwd = "build-mitsuba", env = {PYTHONPATH = "build-mitsuba/python"}, depends-on = ["build-mitsuba"] }
build-mitsuba = { cmd = "ninja -C build-mitsuba", depends-on = ["configure-mitsuba"]}
configure-mitsuba = { cmd = ["cmake", "-G", "Ninja", "-S", "./", "-B", "build-mitsuba"] }

test-drjit = { cmd = "python -m pytest", cwd = "build-drjit", depends-on = ["build-drjit"] }
build-drjit = { cmd = ["ninja", "-C", "build-drjit"], depends-on = ["configure-drjit"]}
configure-drjit = { cmd = "cmake -DDRJIT_ENABLE_TESTS=on -G Ninja -S ext/drjit/ -B build-drjit" }

[dependencies]
cmake = "3.28"
cuda = "12.4"
gcc = "13.2.*"
gxx = "13.2.*"
python = "3.11"
zlib = "1.3.1"
pkg-config = ">=0.29.2,<0.30"
clang = ">=19.1.1,<20"
clangxx = ">=19.1.1,<20"
embree = ">=4.3.3,<5"
pytest = ">=8.3.3,<9"
numpy = ">=2.1.2,<3"
libcxx = ">=19.1.1,<20"
libcxx-devel = ">=19.1.1,<20"
libcxxabi = ">=19.1.1,<20"

# [target.linux-64.activation]
# scripts = ["build-pixi/setpath.sh"]

[target.linux-64.activation.env]
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
