[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "{{cookiecutter.project_name}}"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[tasks]
test-mitsuba = { cmd = "echo $PYTHONPATH && python -m pytest", cwd = "build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
debug-mitsuba = { cmd = "echo $PYTHONPATH && gdb --args python -m pytest", cwd = "build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
build-mitsuba = { cwd = "build-mitsuba", cmd = "ninja", depends-on = [
    "configure-mitsuba",
] }
configure-mitsuba = { cmd = "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -S mitsuba3 -B build-mitsuba" }
clean-mitsuba = { cmd = "rm -r build", cwd = "mitsuba3" }

[dependencies]
cmake = "3.28"
cuda = "12.4"
gcc = "13.2.*"
gxx = "13.2.*"
python = "3.11"
zlib = "1.3.1"
pkg-config = ">=0.29.2,<0.30"
clang = ">=19.1.1,<20"
clangxx = ">=19.1.1,<20"
embree = ">=4.3.3,<5"
pytest = ">=8.3.3,<9"
numpy = ">=2.1.2,<3"
libcxx = ">=19.1.1,<20"
libcxx-devel = ">=19.1.1,<20"
libcxxabi = ">=19.1.1,<20"
ninja = ">=1.12.1,<2"
llvmdev = ">=19.1.4,<20"
lld = ">=19.1.4,<20"
mold = ">=2.35.1,<3"

# [target.linux-64.activation]
# scripts = ["build-pixi/setpath.sh"]

[target.linux-64.activation.env]
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
