[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "{{cookiecutter.project_name}}"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[tasks]

[dependencies]
python = "3.12.*"
gcc = "13.2.*"
gxx = "13.2.*"
cuda = "*"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
torchaudio = ">=2.5.1,<3"
ninja = ">=1.12.1,<2"
pip = ">=24.3.1,<25"
ipython = ">=8.31.0,<9"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.1,<3"
omegaconf = ">=2.3.0,<3"

[pypi-options]
no-build-isolation = ["tinycudann"]

[pypi-dependencies]
tensorboardx = "*"
mitsuba = ">=3.6.0, <4"

tinycudann = { git = "https://github.com/NVlabs/tiny-cuda-nn.git", subdirectory = "bindings/torch", rev = "c91138bcd4c6877c8d5e60e483c0581aafc70cce" }

[target.linux-64.activation.env]
# Have to expose /lib64 for libcuda.so (cuda driver)
LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/lib64:$LIBRARY_PATH"
